# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1291, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.workspace_group = QtWidgets.QGroupBox(self.centralwidget)
        self.workspace_group.setObjectName("workspace_group")
        self.verticalLayout_4.addWidget(self.workspace_group)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1291, 23))
        self.menubar.setObjectName("menubar")
        self.menu_project = QtWidgets.QMenu(self.menubar)
        self.menu_project.setObjectName("menu_project")
        self.menu_tool = QtWidgets.QMenu(self.menubar)
        self.menu_tool.setObjectName("menu_tool")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menu_window = QtWidgets.QMenu(self.menubar)
        self.menu_window.setObjectName("menu_window")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dock_project = QtWidgets.QDockWidget(MainWindow)
        self.dock_project.setMinimumSize(QtCore.QSize(400, 300))
        self.dock_project.setFloating(False)
        self.dock_project.setObjectName("dock_project")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.project_tree = QtWidgets.QTreeView(self.dockWidgetContents)
        self.project_tree.setObjectName("project_tree")
        self.verticalLayout.addWidget(self.project_tree)
        self.dock_project.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock_project)
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionclose = QtWidgets.QAction(MainWindow)
        self.actionclose.setObjectName("actionclose")
        self.actionbuild = QtWidgets.QAction(MainWindow)
        self.actionbuild.setObjectName("actionbuild")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionproject = QtWidgets.QAction(MainWindow)
        self.actionproject.setObjectName("actionproject")
        self.actionpreview = QtWidgets.QAction(MainWindow)
        self.actionpreview.setObjectName("actionpreview")
        self.menu_project.addAction(self.actionnew)
        self.menu_project.addAction(self.actionopen)
        self.menu_project.addAction(self.actionsave)
        self.menu_project.addAction(self.actionclose)
        self.menu_tool.addAction(self.actionbuild)
        self.menu_help.addAction(self.actionabout)
        self.menu_window.addAction(self.actionproject)
        self.menu_window.addAction(self.actionpreview)
        self.menubar.addAction(self.menu_project.menuAction())
        self.menubar.addAction(self.menu_tool.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.menubar.addAction(self.menu_window.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.workspace_group.setTitle(_translate("MainWindow", "工作区"))
        self.menu_project.setTitle(_translate("MainWindow", "项目"))
        self.menu_tool.setTitle(_translate("MainWindow", "工具"))
        self.menu_help.setTitle(_translate("MainWindow", "帮助"))
        self.menu_window.setTitle(_translate("MainWindow", "窗口"))
        self.dock_project.setWindowTitle(_translate("MainWindow", "项目"))
        self.actionnew.setText(_translate("MainWindow", "新建"))
        self.actionopen.setText(_translate("MainWindow", "打开"))
        self.actionsave.setText(_translate("MainWindow", "保存"))
        self.actionclose.setText(_translate("MainWindow", "关闭"))
        self.actionbuild.setText(_translate("MainWindow", "构建"))
        self.actionabout.setText(_translate("MainWindow", "关于"))
        self.actionproject.setText(_translate("MainWindow", "项目"))
        self.actionpreview.setText(_translate("MainWindow", "预览"))


